wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.7
    cli_version: 0.17.7
    framework: keras
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1724422875
    t:
      1:
      - 2
      - 3
      - 5
      - 53
      - 55
      - 105
      2:
      - 2
      - 3
      - 5
      - 53
      - 55
      - 105
      3:
      - 23
      4: 3.11.7
      5: 0.17.7
      8:
      - 3
      - 5
      13: windows-amd64
    visualize:
      Actual vs Predicted Prices:
        panel_type: Vega2
        panel_config:
          panelDefId: wandb/lineseries/v0
          fieldSettings:
            step: step
            lineKey: lineKey
            lineVal: lineVal
          stringSettings:
            title: Actual vs Predicted Prices
            xname: Time
          transform:
            name: tableWithLeafColNames
          userQuery:
            queryFields:
            - name: runSets
              args:
              - name: runSets
                value: ${runSets}
              fields:
              - name: id
                fields: []
              - name: name
                fields: []
              - name: _defaultColorIndex
                fields: []
              - name: summaryTable
                args:
                - name: tableKey
                  value: Actual vs Predicted Prices_table
                fields: []
